### ISSUE TITLE
Putting libidn2 source in this repo? 

### ISSUE THREAD

**Issue by drjohnnyfever1** [tgc/tgcwarev2-for-solaris#1]
Would it be possible to add your re-bootstrapped source of libidn2 to the repo as if it were a bunch of patches, or perhaps putting the source tarball somewhere accessible?

**Comment by tgc** [comment]
I've dropped the archive here:
https://jupiterrise.com/tmp/libidn2-2.0.4-tgcware.tar.gz

Re-bootstrapping is no longer necessary since the release of 2.1.0.  It already has getopt-gnu in bootstrap.conf and it dropped the use of %z so the printf-posix module is not needed either.

I will update the package to 2.1.1a soon.

**Comment by drjohnnyfever1** [comment]
Thanks!
